# Titel

In [1]:
import pandas as pd

#to generate random numbers
from numpy.random import randn

In [2]:
#2dimensional data structures - list
print("Some two-dimensional data types:")
list_2dim = [[10112,"Berlin",3460725],[20095,"Hamburg",1786445],[80331,"München",1353185]]
print("\nThis is a simple 2dim list:")
print (list_2dim)
print(type(list_2dim))

print(list_2dim[1][2])

Some two-dimensional data types:

This is a simple 2dim list:
[[10112, 'Berlin', 3460725], [20095, 'Hamburg', 1786445], [80331, 'München', 1353185]]
<class 'list'>
1786445


In [3]:
#2dimensional data structures - array
array_ran = randn(3,3)
print("\nThis is a simple 2dim array:")
print (array_ran)
print(type(array_ran))

print (array_ran[0,1])


This is a simple 2dim array:
[[ 0.18940282 -0.55897961 -0.15846618]
 [ 2.16695671 -1.25873111 -0.60285834]
 [ 1.40395455  0.49696018  0.77064402]]
<class 'numpy.ndarray'>
-0.5589796132251243


In [4]:
#2dimensional data structures - PANDAS data frame
df = pd.DataFrame(array_ran,index=['ID1','ID2','ID3'],columns=['A1','A2','A3'])
print(type(df))
print("\nThis is a PANDAS dataframe:")
df

<class 'pandas.core.frame.DataFrame'>

This is a PANDAS dataframe:


A1        A2        A3
ID1  0.189403 -0.558980 -0.158466
ID2  2.166957 -1.258731 -0.602858
ID3  1.403955  0.496960  0.770644

In [5]:
#select column
df['A1']

ID1    0.189403
ID2    2.166957
ID3    1.403955
Name: A1, dtype: float64

In [6]:
#select list of columns 
df[['A1','A3']]

A1        A3
ID1  0.189403 -0.158466
ID2  2.166957 -0.602858
ID3  1.403955  0.770644

In [7]:
#create new column
df['A1+A2']=df['A1']+df['A2']
df

A1        A2        A3     A1+A2
ID1  0.189403 -0.558980 -0.158466 -0.369577
ID2  2.166957 -1.258731 -0.602858  0.908226
ID3  1.403955  0.496960  0.770644  1.900915

In [8]:
#drop column temporarily
df.drop('A1+A2',axis=1)

A1        A2        A3
ID1  0.189403 -0.558980 -0.158466
ID2  2.166957 -1.258731 -0.602858
ID3  1.403955  0.496960  0.770644

In [9]:
df

A1        A2        A3     A1+A2
ID1  0.189403 -0.558980 -0.158466 -0.369577
ID2  2.166957 -1.258731 -0.602858  0.908226
ID3  1.403955  0.496960  0.770644  1.900915

In [12]:
#drop column permanently
df.drop('A1+A2',axis=1,inplace=True)

KeyError: "['A1+A2'] not found in axis"

In [11]:
df

A1        A2        A3
ID1  0.189403 -0.558980 -0.158466
ID2  2.166957 -1.258731 -0.602858
ID3  1.403955  0.496960  0.770644

In [13]:
#select row
df.loc['ID1']

A1    0.189403
A2   -0.558980
A3   -0.158466
Name: ID1, dtype: float64

In [14]:
#drop row temp
df.drop('ID1',axis=0)

A1        A2        A3
ID2  2.166957 -1.258731 -0.602858
ID3  1.403955  0.496960  0.770644

In [15]:
#select rows and columns at once
df.loc[['ID2','ID3'],['A1','A2']]

A1        A2
ID2  2.166957 -1.258731
ID3  1.403955  0.496960

In [16]:
df

A1        A2        A3
ID1  0.189403 -0.558980 -0.158466
ID2  2.166957 -1.258731 -0.602858
ID3  1.403955  0.496960  0.770644

In [17]:
#conditional selection
df >= 0

A1     A2     A3
ID1  True  False  False
ID2  True  False  False
ID3  True   True   True

In [18]:
#conditional selection
df[df['A3']>=0]
#df[df['A3']<0]['A1']

A1       A2        A3
ID3  1.403955  0.49696  0.770644

In [19]:
#descriptive statistics
df.describe()

A1        A2        A3
count  3.000000  3.000000  3.000000
mean   1.253438 -0.440250  0.003107
std    0.997332  0.883847  0.700861
min    0.189403 -1.258731 -0.602858
25%    0.796679 -0.908855 -0.380662
50%    1.403955 -0.558980 -0.158466
75%    1.785456 -0.031010  0.306089
max    2.166957  0.496960  0.770644

In [20]:
#non-missing values and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, ID1 to ID3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A1      3 non-null      float64
 1   A2      3 non-null      float64
 2   A3      3 non-null      float64
dtypes: float64(3)
memory usage: 204.0+ bytes
